# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaoPiao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MBProgressHUD', '~> 0.8'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry', '~> 1.0.0'
  pod 'SDWebImage', '~> 3.7.6'
  pod 'MJRefresh', '~>3.1.12'
  pod 'LKDBHelper', '~>2.1.8'
  pod 'TKAlert&TKActionSheet', '~> 1.0.23'
  pod 'JPush', '~> 2.1.6'
  pod 'ReactiveCocoa','2.1.8'
  pod 'MZTimerLabel', '~> 0.5.4'
  pod 'LDProgressView', '~> 1.2.1'
  pod 'DLAlertView', '~> 1.2.5'
  pod 'SDiPhoneVersion', '~> 1.1.2'
  pod 'BTBadgeView', '~> 1.3'
  #pod 'WechatOpenSDK', '~> 1.8.0'
  # Pods for TaoPiao

  target 'TaoPiaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaoPiaoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
